### ISSUE TITLE
requirment

### ISSUE THREAD

**Issue by soltani123-Bilel** [ylhsieh/ppi_lstm_rnn_keras#2]
requirment please

**Comment by ylhsieh** [comment]
Hi there, this repo has not been updated for quite a while. As far as I can remember, you need
```
numpy
tensorflow<=2.0
keras
scikit-learn
```

**Comment by Soltani-Bilel** [comment]
Python vesion

**Comment by ylhsieh** [comment]
I believe it was 2.7
